### ISSUE TITLE
ODbL 1.0 violation

### ISSUE THREAD

**Issue by Nakaner** [go-spatial/tegola-example-data#2]
OpenStreetMap data [is published](https://www.openstreetmap.org/copyright) under the terms of the [Open Database License 1.0](https://opendatacommons.org/licenses/odbl/1.0/index.html). Please comply with the terms.

To be precise, the following requirements are not met by this repository:

> 4.2 Notices. If You Publicly Convey this Database, any Derivative
Database, or the Database as part of a Collective Database, then You
must:
> 
> a. Do so only under the terms of this License or another license
permitted under Section 4.4;
> 
> b. Include a copy of this License (or, as applicable, a license
permitted under Section 4.4) or its Uniform Resource Identifier (URI)
with the Database or Derivative Database, including both in the
Database or Derivative Database and in any relevant documentation; and
> 
> c. Keep intact any copyright or Database Right notices and notices
that refer to this License.
> 
> d. If it is not possible to put the required notices in a particular
file due to its structure, then You must include the notices in a
location (such as a relevant directory) where users would be likely to
look for it.
> 
> 4.3 […]
> 
> 4.4 Share alike.
> 
> a. Any Derivative Database that You Publicly Use must be only under
the terms of:
> 
> i. This License;
> 
> ii. A later version of this License similar in spirit to this
License; or
> 
> iii. A compatible license.
> 
> If You license the Derivative Database under one of the licenses
mentioned in (iii), You must comply with the terms of that license.
> 
> b. For the avoidance of doubt, Extraction or Re-utilisation of the
whole or a Substantial part of the Contents into a new database is a
Derivative Database and must comply with Section 4.4.

I neither see an attribution nor the text of the license or a link to it in this repository.

**Comment by ARolek** [comment]
@Nakaner would you be willing to submit a PR of what you would like to see published in this repo in order to bring it into compliance?

**Comment by Nakaner** [comment]
I am sorry but it is not my task to fullfill simple requirements which have to be fulfilled by someone else. You basically need to provide the license and attribution with the repository or the file. Just put a text file into the tarball.
